apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default
- user-cluster-roles.yaml

namespace: opendatahub

patches:
- path: remove-namespace.yaml
- path: inferenceservice-config-patch.yaml
- path: set-resources-manager-patch.yaml

replacements:
- source:
    kind: ConfigMap
    name: kserve-parameters
    fieldpath: data.kserve-controller
  targets:
  - select:
      kind: Deployment
      name: kserve-controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].image
- source:
    kind: ConfigMap
    name: kserve-parameters
    fieldPath: data.kserve-storage-initializer
  targets:
  - select:
      kind: ConfigMap
      name: inferenceservice-config
    fieldPaths:
    - data.storageInitializer
- source:
    kind: ConfigMap
    name: kserve-parameters
    fieldPath: data.kserve-agent
  targets:
  - select:
      kind: ConfigMap
      name: inferenceservice-config
    fieldPaths:
    - data.logger
    - data.batcher
    - data.agent
- source:
    kind: ConfigMap
    name: kserve-parameters
    fieldPath: data.kserve-router
  targets:
  - select:
      kind: ConfigMap
      name: inferenceservice-config
    fieldPaths:
    - data.router

configMapGenerator:
- envs:
  - params.env
  name: kserve-parameters

generatorOptions:
  disableNameSuffixHash: true

configurations:
  - params.yaml
